version: 2

sources:
  - name: retail
    database: RAW
    schema: retail
    tables:
      - name: addresses
      - name: customers
      - name: products
      - name: orders
        loaded_at_field: updated_at
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
      - name: order_items
      - name: payments
      - name: order_events
      - name: payment_events
        loaded_at_field: event_timestamp
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
